/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.smartmachine.io/crdb-operator/pkg/apis/db/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCockroachDBs implements CockroachDBInterface
type FakeCockroachDBs struct {
	Fake *FakeDbV1alpha1
	ns   string
}

var cockroachdbsResource = schema.GroupVersionResource{Group: "db.smartmachine.io", Version: "v1alpha1", Resource: "cockroachdbs"}

var cockroachdbsKind = schema.GroupVersionKind{Group: "db.smartmachine.io", Version: "v1alpha1", Kind: "CockroachDB"}

// Get takes name of the cockroachDB, and returns the corresponding cockroachDB object, and an error if there is any.
func (c *FakeCockroachDBs) Get(name string, options v1.GetOptions) (result *v1alpha1.CockroachDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cockroachdbsResource, c.ns, name), &v1alpha1.CockroachDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CockroachDB), err
}

// List takes label and field selectors, and returns the list of CockroachDBs that match those selectors.
func (c *FakeCockroachDBs) List(opts v1.ListOptions) (result *v1alpha1.CockroachDBList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cockroachdbsResource, cockroachdbsKind, c.ns, opts), &v1alpha1.CockroachDBList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CockroachDBList{ListMeta: obj.(*v1alpha1.CockroachDBList).ListMeta}
	for _, item := range obj.(*v1alpha1.CockroachDBList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cockroachDBs.
func (c *FakeCockroachDBs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cockroachdbsResource, c.ns, opts))

}

// Create takes the representation of a cockroachDB and creates it.  Returns the server's representation of the cockroachDB, and an error, if there is any.
func (c *FakeCockroachDBs) Create(cockroachDB *v1alpha1.CockroachDB) (result *v1alpha1.CockroachDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cockroachdbsResource, c.ns, cockroachDB), &v1alpha1.CockroachDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CockroachDB), err
}

// Update takes the representation of a cockroachDB and updates it. Returns the server's representation of the cockroachDB, and an error, if there is any.
func (c *FakeCockroachDBs) Update(cockroachDB *v1alpha1.CockroachDB) (result *v1alpha1.CockroachDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cockroachdbsResource, c.ns, cockroachDB), &v1alpha1.CockroachDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CockroachDB), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCockroachDBs) UpdateStatus(cockroachDB *v1alpha1.CockroachDB) (*v1alpha1.CockroachDB, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cockroachdbsResource, "status", c.ns, cockroachDB), &v1alpha1.CockroachDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CockroachDB), err
}

// Delete takes name of the cockroachDB and deletes it. Returns an error if one occurs.
func (c *FakeCockroachDBs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cockroachdbsResource, c.ns, name), &v1alpha1.CockroachDB{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCockroachDBs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cockroachdbsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CockroachDBList{})
	return err
}

// Patch applies the patch and returns the patched cockroachDB.
func (c *FakeCockroachDBs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CockroachDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cockroachdbsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CockroachDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CockroachDB), err
}
