/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	dbv1alpha1 "go.smartmachine.io/crdb-operator/pkg/apis/db/v1alpha1"
	versioned "go.smartmachine.io/crdb-operator/pkg/client/clientset/versioned"
	internalinterfaces "go.smartmachine.io/crdb-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "go.smartmachine.io/crdb-operator/pkg/client/listers/db/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CockroachDBInformer provides access to a shared informer and lister for
// CockroachDBs.
type CockroachDBInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CockroachDBLister
}

type cockroachDBInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCockroachDBInformer constructs a new informer for CockroachDB type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCockroachDBInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCockroachDBInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCockroachDBInformer constructs a new informer for CockroachDB type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCockroachDBInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DbV1alpha1().CockroachDBs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DbV1alpha1().CockroachDBs(namespace).Watch(options)
			},
		},
		&dbv1alpha1.CockroachDB{},
		resyncPeriod,
		indexers,
	)
}

func (f *cockroachDBInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCockroachDBInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cockroachDBInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dbv1alpha1.CockroachDB{}, f.defaultInformer)
}

func (f *cockroachDBInformer) Lister() v1alpha1.CockroachDBLister {
	return v1alpha1.NewCockroachDBLister(f.Informer().GetIndexer())
}
