apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cockroachdbs.db.smartmachine.io
spec:
  group: db.smartmachine.io
  names:
    kind: CockroachDB
    listKind: CockroachDBList
    plural: cockroachdbs
    singular: cockroachdb
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            client:
              properties:
                enable:
                  type: boolean
              type: object
            cluster:
              properties:
                image:
                  type: string
                limitMemory:
                  type: string
                maxUnavailable:
                  format: int64
                  type: integer
                requestMemory:
                  type: string
                size:
                  description: Size is the number of nodes the cluster should have
                  format: int32
                  type: integer
                storagePerNode:
                  type: string
              type: object
            dashboard:
              properties:
                enable:
                  type: boolean
                nodePort:
                  format: int32
                  type: integer
              type: object
          type: object
        status:
          properties:
            initialised:
              type: boolean
            nodes:
              description: Nodes are the names of the cockroachdb pods
              items:
                properties:
                  name:
                    type: string
                  ready:
                    type: boolean
                  serving:
                    type: boolean
                required:
                - name
                - ready
                - serving
                type: object
              type: array
            readyforinit:
              type: boolean
            serving:
              type: boolean
          required:
          - readyforinit
          - initialised
          - serving
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
