style: github
template: CHANGELOG.tpl.md
info:
  title: CockroachDB Operator CHANGELOG
  repository_url: https://github.com/smartmachine/crdb-operator
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - pr
  commit_groups:
    group_by: Type
    sort_by: Scope
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      pr: Pull Requests
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - #
  refs:
    actions:
      - Closes
      - Fixes
  merges:
    pattern: "^Merge branch '(\\w+)'$"
    pattern_maps:
      - Source
  notes:
    keywords:
      - BREAKING CHANGE
