/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "go.smartmachine.io/crdb-operator/pkg/apis/db/v1alpha1"
	scheme "go.smartmachine.io/crdb-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CockroachDBsGetter has a method to return a CockroachDBInterface.
// A group's client should implement this interface.
type CockroachDBsGetter interface {
	CockroachDBs(namespace string) CockroachDBInterface
}

// CockroachDBInterface has methods to work with CockroachDB resources.
type CockroachDBInterface interface {
	Create(*v1alpha1.CockroachDB) (*v1alpha1.CockroachDB, error)
	Update(*v1alpha1.CockroachDB) (*v1alpha1.CockroachDB, error)
	UpdateStatus(*v1alpha1.CockroachDB) (*v1alpha1.CockroachDB, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CockroachDB, error)
	List(opts v1.ListOptions) (*v1alpha1.CockroachDBList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CockroachDB, err error)
	CockroachDBExpansion
}

// cockroachDBs implements CockroachDBInterface
type cockroachDBs struct {
	client rest.Interface
	ns     string
}

// newCockroachDBs returns a CockroachDBs
func newCockroachDBs(c *DbV1alpha1Client, namespace string) *cockroachDBs {
	return &cockroachDBs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cockroachDB, and returns the corresponding cockroachDB object, and an error if there is any.
func (c *cockroachDBs) Get(name string, options v1.GetOptions) (result *v1alpha1.CockroachDB, err error) {
	result = &v1alpha1.CockroachDB{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cockroachdbs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CockroachDBs that match those selectors.
func (c *cockroachDBs) List(opts v1.ListOptions) (result *v1alpha1.CockroachDBList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CockroachDBList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cockroachdbs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cockroachDBs.
func (c *cockroachDBs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cockroachdbs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cockroachDB and creates it.  Returns the server's representation of the cockroachDB, and an error, if there is any.
func (c *cockroachDBs) Create(cockroachDB *v1alpha1.CockroachDB) (result *v1alpha1.CockroachDB, err error) {
	result = &v1alpha1.CockroachDB{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cockroachdbs").
		Body(cockroachDB).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cockroachDB and updates it. Returns the server's representation of the cockroachDB, and an error, if there is any.
func (c *cockroachDBs) Update(cockroachDB *v1alpha1.CockroachDB) (result *v1alpha1.CockroachDB, err error) {
	result = &v1alpha1.CockroachDB{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cockroachdbs").
		Name(cockroachDB.Name).
		Body(cockroachDB).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cockroachDBs) UpdateStatus(cockroachDB *v1alpha1.CockroachDB) (result *v1alpha1.CockroachDB, err error) {
	result = &v1alpha1.CockroachDB{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cockroachdbs").
		Name(cockroachDB.Name).
		SubResource("status").
		Body(cockroachDB).
		Do().
		Into(result)
	return
}

// Delete takes name of the cockroachDB and deletes it. Returns an error if one occurs.
func (c *cockroachDBs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cockroachdbs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cockroachDBs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cockroachdbs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cockroachDB.
func (c *cockroachDBs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CockroachDB, err error) {
	result = &v1alpha1.CockroachDB{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cockroachdbs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
